// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UPHC.SurveillanceDashboard.Data;

#nullable disable

namespace UPHC.SurveillanceDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.CaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressOfPatient")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCommunicable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LabConfirmedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OnsetDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("CaseRecords");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FacilityAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacilityAddress = "Unit-4",
                            FacilityName = "UCHC Unit-4",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            FacilityAddress = "Dumduma",
                            FacilityName = "UCHC Dumduma",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            FacilityAddress = "Unit-8",
                            FacilityName = "UCHC Unit-8",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            FacilityAddress = "Old Town,Lingaraj nagar",
                            FacilityName = "UCHC BMC Hospital",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            FacilityAddress = "Kharvela Nagar",
                            FacilityName = "Unit-3 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            FacilityAddress = "Unit-4,Near AG Colony",
                            FacilityName = "Unit-4 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            FacilityAddress = "Unit-8",
                            FacilityName = "Unit-8 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            FacilityAddress = "Unit-9 Industrial Colony",
                            FacilityName = "Unit-9 UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            FacilityAddress = "Saheed Nagar",
                            FacilityName = "Saheed Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            FacilityAddress = "Satya Nagar,Near Kali Mandir",
                            FacilityName = "Satya Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            FacilityAddress = "Rental Colony, IRC Village",
                            FacilityName = "Baramunda UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            FacilityAddress = "IRC Village, Nayapalli",
                            FacilityName = "IRC Village UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            FacilityAddress = "GGP Colony, Rasulgarh",
                            FacilityName = "Rasulgarh UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            FacilityAddress = "Gadeswar,Near RI Office Kalarahanga",
                            FacilityName = "Gadakan UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            FacilityAddress = "Pokhariput,Ward No-62",
                            FacilityName = "Pokhariput UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            FacilityAddress = "CS Pur HB Colony,Ward No-8",
                            FacilityName = "Chandrasekharpur UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            FacilityAddress = "Niladri Vihar, Sector-I",
                            FacilityName = "Niladri Vihar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 18,
                            FacilityAddress = "BJB Nagar,Near BJB Nagar Hata",
                            FacilityName = "Bjb Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            FacilityAddress = "Bhimatangi Housing Board area",
                            FacilityName = "Bhimatangi UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            FacilityAddress = "Kapilaprasad Village area",
                            FacilityName = "Kapilaprasad UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 21,
                            FacilityAddress = "Badagada Village,Brit area",
                            FacilityName = "Badagada UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            FacilityAddress = "Jharapada Village area",
                            FacilityName = "Jharapada UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            FacilityAddress = "Bharatpur Slum,Mahalaxmi Vihar",
                            FacilityName = "Bharatpur UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            FacilityAddress = "Patia Village,Damana area",
                            FacilityName = "Patia UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            FacilityAddress = "VSS Nagar Housing Board area",
                            FacilityName = "VSS Nagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            FacilityAddress = "Laxmisagar Village area",
                            FacilityName = "Laxmisagar UPHC",
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            FacilityAddress = "Ward 12, near Kalyan Mandap",
                            FacilityName = "VSS Nagar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 28,
                            FacilityAddress = "Ward 14, Sector 1",
                            FacilityName = "Niladri Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 29,
                            FacilityAddress = "Ward 59, near Samantarapur Square",
                            FacilityName = "Samantarapur UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 30,
                            FacilityAddress = "Ward 49, Shreekhetra Vihar",
                            FacilityName = "Aiginia UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 31,
                            FacilityAddress = "Ward 65, Kalinga Vihar K-9",
                            FacilityName = "Patrapada UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 32,
                            FacilityAddress = "L170, Baramunda Housing Board Colony",
                            FacilityName = "Baramunda HB UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 33,
                            FacilityAddress = "Satya Vihar, Ward 5",
                            FacilityName = "Chakaisiani UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 34,
                            FacilityAddress = "Acharya Vihar, Ward 27",
                            FacilityName = "Acharya Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 35,
                            FacilityAddress = "Kalarahanga, near KIIT area",
                            FacilityName = "Kalarahanga UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 36,
                            FacilityAddress = "Sainik School Road, Ward 5",
                            FacilityName = "Palasuni UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 37,
                            FacilityAddress = "Subudhipur, Aiginia area",
                            FacilityName = "Subudhipur UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 38,
                            FacilityAddress = "Badagada Brit Colony",
                            FacilityName = "Badagada Sabarasahi UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 39,
                            FacilityAddress = "Hanspal, Balianta area",
                            FacilityName = "Hanspal UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 40,
                            FacilityAddress = "Gadakana area, Ward 9",
                            FacilityName = "Gadakana UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 41,
                            FacilityAddress = "Jharapada, near Jail area",
                            FacilityName = "Jharapada UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 42,
                            FacilityAddress = "Sailashree Vihar, Ward 7",
                            FacilityName = "Sailashree Vihar UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 43,
                            FacilityAddress = "Unit-6 area, Ward 46",
                            FacilityName = "Unit-6 UHWC",
                            Type = 4
                        },
                        new
                        {
                            Id = 44,
                            FacilityAddress = "Dumuduma Housing Board Phase-III",
                            FacilityName = "Dumuduma UHWC",
                            Type = 4
                        });
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.FacilityReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CHCId")
                        .HasColumnType("integer");

                    b.Property<int>("UPHCId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CHCId");

                    b.HasIndex("UPHCId", "CHCId")
                        .IsUnique();

                    b.ToTable("FacilityReferrals", t =>
                        {
                            t.HasCheckConstraint("CK_NoSelfReferral", "\"UPHCId\" <> \"CHCId\"");
                        });
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("CaseRecordId", "Type")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPHC.SurveillanceDashboard.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.ApplicationUser", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.Facility", "Facility")
                        .WithMany("Users")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.CaseRecord", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.Facility", "Facility")
                        .WithMany("CaseRecords")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UPHC.SurveillanceDashboard.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.FacilityReferral", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.Facility", "CHC")
                        .WithMany("CHCReferrals")
                        .HasForeignKey("CHCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UPHC.SurveillanceDashboard.Models.Facility", "UPHC")
                        .WithMany("UPHCReferrals")
                        .HasForeignKey("UPHCId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CHC");

                    b.Navigation("UPHC");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.Notification", b =>
                {
                    b.HasOne("UPHC.SurveillanceDashboard.Models.CaseRecord", "CaseRecord")
                        .WithMany("Notifications")
                        .HasForeignKey("CaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UPHC.SurveillanceDashboard.Models.Facility", "Facility")
                        .WithMany("Notifications")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseRecord");

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.CaseRecord", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("UPHC.SurveillanceDashboard.Models.Facility", b =>
                {
                    b.Navigation("CHCReferrals");

                    b.Navigation("CaseRecords");

                    b.Navigation("Notifications");

                    b.Navigation("UPHCReferrals");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
